"""Add completed field to Milestone

Revision ID: 60dcd021a4b7
Revises: 7b3573f092ec
Create Date: 2025-05-14 09:54:58.035081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60dcd021a4b7'
down_revision = '7b3573f092ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milestone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milestone', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
